name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm install mongoose express react react-router-dom cors body-parser

      - name: Run tests
        run: npm test

      - name: Build React app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to production
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          OTHER_SECRET: ${{ secrets.OTHER_SECRET }}
        run: |
          # Your deployment script or commands here
          npm run deploy
